apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  mongo-uri: bW9uZ29kYitzcnY6Ly9zYW1heWd1cHRhOnNhbWF5MTIzQGNsdXN0ZXIwLjc2dHhjYjYubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw

